function G = G_fun(a2,a3,a6,g0,m2,m3,m4,m5,m6,q1,q2,q4,q5)
%G_FUN
%    G = G_FUN(A2,A3,A6,G0,M2,M3,M4,M5,M6,Q1,Q2,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    06-Mar-2020 14:29:27

G = [-m4.*conj(g0).*(a2.*sin(q1)-a3.*cos(q1).*sin(q2))-m3.*conj(g0).*(a2.*sin(q1)-(a3.*cos(q1).*sin(q2))./2.0)-m5.*conj(g0).*(a2.*sin(q1)-a3.*cos(q1).*sin(q2))-m6.*conj(g0).*(a2.*sin(q1)+a6.*(sin(q5).*(sin(q1).*sin(q4)-cos(q1).*cos(q2).*cos(q4))-cos(q1).*cos(q5).*sin(q2))-a3.*cos(q1).*sin(q2))-(a2.*m2.*conj(g0).*sin(q1))./2.0;m6.*conj(g0).*(a6.*(cos(q2).*cos(q5).*sin(q1)-cos(q4).*sin(q1).*sin(q2).*sin(q5))+a3.*cos(q2).*sin(q1))+(a3.*m3.*conj(g0).*cos(q2).*sin(q1))./2.0+a3.*m4.*conj(g0).*cos(q2).*sin(q1)+a3.*m5.*conj(g0).*cos(q2).*sin(q1);0.0;a6.*m6.*conj(g0).*sin(q5).*(cos(q1).*cos(q4)-cos(q2).*sin(q1).*sin(q4));a6.*m6.*conj(g0).*(cos(q5).*(cos(q1).*sin(q4)+cos(q2).*cos(q4).*sin(q1))-sin(q1).*sin(q2).*sin(q5));0.0];
