function Lf2h = Lf2h_fun(B,C,b2,gravity,l,q)
%LF2H_FUN
%    LF2H = LF2H_FUN(B,C,B2,GRAVITY,L,Q1,Q4)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    28-Dec-2021 17:34:13

q1 = q(1);
q2 = q(2);
q3 = q(3);
q4 = q(4);

Lf2h = -(b2.*q4+B.*gravity.*l.*sin(q1))./(C+B.*l.*cos(q1));
