function LgLfh = LgLfh_fun(B,C,D,l,q)
%LGLFH_FUN
%    LGLFH = LGLFH_FUN(B,C,D,L,Q1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    28-Dec-2021 17:34:14

q1 = q(1);
q2 = q(2);
q3 = q(3);
q4 = q(4);

LgLfh = 1.0./(D.*(C+B.*l.*cos(q1)));
