function f = f_fun(B,C,D,b1,b2,gravity,l,q)
%F_FUN
%    F = F_FUN(B,C,D,B1,B2,GRAVITY,L,Q1,Q2,Q4)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    02-Oct-2021 14:20:10

q1 = q(1);
q2 = q(2);
q3 = q(3);
q4 = q(4);

t2 = cos(q1);
t3 = sin(q1);
t4 = b2.*q4;
t5 = 1.0./D;
t6 = B.*l.*t2;
t7 = B.*gravity.*l.*t3;
t8 = C+t6;
t9 = 1.0./t8;
f = [q2;-t5.*t7-b1.*q2.*t5+(t5.*t6.*t9.*(t4-t7))./C;q4;-t9.*(t4+t7)];
