function f = f_fun(B,C,D,b1,b2,g0,l,q)
%F_FUN
%    F = F_FUN(B,C,D,B1,B2,G0,L,Q1,Q2,Q4)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-Sep-2021 14:42:45

q1 = q(1);
q2 = q(2);
q3 = q(3);
q4 = q(4);

t2 = cos(q1);
t3 = sin(q1);
t4 = b2.*q4;
t5 = 1.0./C;
t6 = 1.0./D;
t7 = B.*l.*t2;
t8 = B.*g0.*l.*t3;
t9 = C+t7;
t10 = 1.0./t9;
f = [q2;-t5.*t8-b1.*q2.*t6+t5.*t6.*t7.*t10.*(t4-t8);q4;-t10.*(t4+t8)];
