function out1 = fx_fun(B,C,b2,gravity,l,q)
%FX_FUN
%    OUT1 = FX_FUN(B,C,B2,GRAVITY,L,Q1,Q4)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    29-Nov-2021 17:45:01

q1 = q(1);
q2 = q(2);
q3 = q(3);
q4 = q(4);

out1 = -(b2.*q4+B.*gravity.*l.*sin(q1))./(C+B.*l.*cos(q1));
