function out1 = gtheta_fun(B,C,D,l,q)
%GTHETA_FUN
%    OUT1 = GTHETA_FUN(B,C,D,L,Q1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    29-Nov-2021 17:45:01

q1 = q(1);
q2 = q(2);
q3 = q(3);
q4 = q(4);

t2 = cos(q1);
out1 = (B.*l.*t2)./(D.*(C+B.*l.*t2));
