function h = h_fun(q)
%H_FUN
%    H = H_FUN(Q1,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-Sep-2021 14:42:46

q1 = q(1);
q2 = q(2);
q3 = q(3);
q4 = q(4);

h = [q1;q3];
