function h = h_fun(l,q)
%H_FUN
%    H = H_FUN(L,Q1,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    04-Dec-2021 17:25:46

q1 = q(1);
q2 = q(2);
q3 = q(3);
q4 = q(4);

h = q3+l.*sin(q1);
