function Lf2h2 = Lf2h2_fun(B,C,b2,gravity,l,q)
%LF2H2_FUN
%    LF2H2 = LF2H2_FUN(B,C,B2,GRAVITY,L,Q1,Q4)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    02-Oct-2021 14:23:16

q1 = q(1);
q2 = q(2);
q3 = q(3);
q4 = q(4);

Lf2h2 = -(b2.*q4+B.*gravity.*l.*sin(q1))./(C+B.*l.*cos(q1));
