function Lf2h1 = Lf2h1_fun(B,C,D,b1,b2,gravity,l,q)
%LF2H1_FUN
%    LF2H1 = LF2H1_FUN(B,C,D,B1,B2,GRAVITY,L,Q1,Q2,Q4)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    02-Oct-2021 14:23:16

q1 = q(1);
q2 = q(2);
q3 = q(3);
q4 = q(4);

t2 = cos(q1);
t3 = sin(q1);
t4 = 1.0./D;
Lf2h1 = -b1.*q2.*t4-B.*gravity.*l.*t3.*t4+(B.*l.*t2.*t4.*(b2.*q4-B.*gravity.*l.*t3))./(C.*(C+B.*l.*t2));
