function LgLfh1 = LgLfh1_fun(B,C,D,l,q)
%LGLFH1_FUN
%    LGLFH1 = LGLFH1_FUN(B,C,D,L,Q1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    02-Oct-2021 14:23:16

q1 = q(1);
q2 = q(2);
q3 = q(3);
q4 = q(4);

t2 = cos(q1);
LgLfh1 = (B.*l.*t2)./(D.*(C+B.*l.*t2));
