function LgLfh1 = LgLfh1_fun(B,C,D,l,q)
%LGLFH1_FUN
%    LGLFH1 = LGLFH1_FUN(B,C,D,L,Q1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    23-Sep-2021 18:39:14

q1 = q(1);

t2 = cos(q1);
LgLfh1 = (B.*l.*t2)./(D.*(C+B.*l.*t2));
