function Lfh = Lfh_fun(q)
%LFH_FUN
%    LFH = LFH_FUN(Q4)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    28-Dec-2021 17:34:13

q1 = q(1);
q2 = q(2);
q3 = q(3);
q4 = q(4);

Lfh = q4;
