function h = h_fun(q)
%H_FUN
%    H = H_FUN(Q1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    28-Dec-2021 17:27:46

q1 = q(1);
q2 = q(2);
q3 = q(3);
q4 = q(4);

h = q1;
