function LgLfh = LgLfh_fun(B,C,D,l,q)
%LGLFH_FUN
%    LGLFH = LGLFH_FUN(B,C,D,L,Q1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    10-Dec-2021 15:40:01

q1 = q(1);
q2 = q(2);
q3 = q(3);
q4 = q(4);

t2 = cos(q1);
t3 = 1.0./D;
t4 = B.*l.*t2;
t5 = C+t4;
t6 = 1.0./t5;
LgLfh = t3.*t6+l.*t2.*t3.*t4.*t6;
