function Lfh = Lfh_fun(q)
%LFH_FUN
%    LFH = LFH_FUN(Q2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    06-Jan-2022 16:16:56

q1 = q(1);
q2 = q(2);
q3 = q(3);
q4 = q(4);

Lfh = q2;
