function LgLfh = LgLfh_fun(B,C,D,l,q)
%LGLFH_FUN
%    LGLFH = LGLFH_FUN(B,C,D,L,Q1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    06-Jan-2022 16:16:56

q1 = q(1);
q2 = q(2);
q3 = q(3);
q4 = q(4);

t2 = cos(q1);
LgLfh = (B.*l.*t2)./(D.*(C+B.*l.*t2));
